version: 0.2

phases:
  install:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - export BUILD_TAG=build-`echo build-$CODEBUILD_BUILD_ID | awk -F":" '{print $2}'`
      - export IMAGE_TAG=$IMAGE_REPO_NAME:$BUILD_TAG
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$BUILD_TAG
  build:
    commands:
      - docker build -t $IMAGE_TAG .
      - docker tag $IMAGE_TAG $IMAGE_URI
  post_build:
    commands:
      - docker push $IMAGE_URI
      - printf '{"ImageURI":"%s"}' $IMAGE_URI > imageDetail.json
      - envsubst < taskdef.json > taskdefinition.json

artifacts:
  files:
    - imageDetail.json
    - appspec.yml
    - taskdefinition.json
